# 01:Definição das redes e volumes

networks:
  app-network:
    driver: bridge  #Driver de rede 'bridge' permite que os containers se comuniquem entre si

volumes:
  postgres_data:  #Volume para a persistência dos dados do banco PostgreSQL

# 02:Serviços

services:
  #PostgreSQL
  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_USER: postgres  #Usuário padrão para o banco de dados
      POSTGRES_PASSWORD: secretpass  #Senha do usuário PostgreSQL
      POSTGRES_DB: postgres  #Nome do banco de dados a ser criado
    ports:
      - "5432:5432"  #Mapeia a porta 5432 do container para a porta 5432 do host para permitir o acesso ao banco de dados
    volumes:
      - postgres_data:/var/lib/postgresql/data  #Mapeia o volume 'postgres_data' para a persistência dos dados
    networks:
      - app-network  #Serviço PostgreSQL associado à rede 'app-network', permite a comunicação com os outros containers
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]  #Verificação de saúde para garantir que o PostgreSQL está ready
      interval: 10s  #Intervalo entre as verificações
      timeout: 5s  #Tempo limite para a resposta do comando
      retries: 5  #Número de tentativas antes de considerar o serviço como falho
  
  #Serviço Backend (Flask)
  backend:
    build:
      context: ./backend  #Caminho relativo para o diretório onde o Dockerfile do backend
      dockerfile: Dockerfile  #Nome do arquivo Dockerfile do backend
    container_name: flask  #Nome do container do serviço backend
    depends_on:
      postgres:
        condition: service_healthy  #Dependência da "saúde" do Postgree
    networks:
      - app-network  #Conexão à rede 'app-network' para comunicação com o PostgreSQL e o frontend
    ports:
      - "5000:5000"  #Expor a porta 5000 do backend (container) para a porta 5000 do host
  
  #Serviço NGINX
  frontend:
    build: 
      context: ./frontend  # Caminho para o diret[orio do Dockerfile do frontend
      dockerfile: Dockerfile  #Nome do arquivo Dockerfile do frontend
    container_name: nginx  #Nome do container do serviço frontend
    depends_on:
      - backend  #Dependência da "saúde" do backend
    networks:
      - app-network  #Conexão à mesma mesma rede que o backend e o PostgreSQL
    ports:
      - "80:80"  #Expor porta 80 do NGINX (container) para a porta 80 do host
